code header fixes
MicrosoftDocs/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw pull request #7
Opened 2018-07-12 20:01 UTC by atikmapari

2018-07-12 20:03 UTC, jmazzotta commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201807122001566351-7%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EE28F25C6QvhFl6OkPu1d3YKaapgWuiKs7CGa%2BaPYus%3D&st=2018-07-12T19%3A58%3A16Z&se=2018-08-12T20%3A03%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-12 22:32 UTC, jmazzotta commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server-overview.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server-overview?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/what’s-new-with-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201807122231074869-7%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Gi3GC6k4THn%2FvIIUza52li8XjyzmJkhKVABfJW5WoVs%3D&st=2018-07-12T22%3A27%3A19Z&se=2018-08-12T22%3A32%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-17 17:58 UTC, nivnar requested changes
Bold text has been fixed on master and this PR has old values resulting in conflicts. Please re-send PR with only code header changes. Thanks

2018-07-17 18:39 UTC, jmazzotta commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server-overview.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server-overview?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/what’s-new-with-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201807171837471612-7%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=l4ymfHvr6AiOIS6r49s1IbKqBEaUA0iplb7CpJgLNvE%3D&st=2018-07-17T18%3A33%3A59Z&se=2018-08-17T18%3A38%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-17 19:45 UTC, jmazzotta commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server-overview.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server-overview?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/what’s-new-with-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201807171944252145-7%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xVmzigJ8tKaDRFImu%2BdYVkq4bRR81SqFEJOyGqrz1VE%3D&st=2018-07-17T19%3A40%3A44Z&se=2018-08-17T19%3A45%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-17 19:46 UTC, jmazzotta commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server-overview.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server-overview?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013?branch=pr-zh-tw-7) |
[Web-Apps-Server-loc/what’s-new-with-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/Code-header-fixes/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013?branch=pr-zh-tw-7) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201807171945475488-7%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3uuTu23VqHJEfDu4NFo6VtYwUvVwsw%2BRyHL0qm5yt2k%3D&st=2018-07-17T19%3A41%3A58Z&se=2018-08-17T19%3A46%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-17 19:47 UTC, merged